### PR TITLE
support for tor 0.3.1.7

### PR DESCRIPTION
**Pull request by marcotessarotto**
includes build of tor 0.3.1.7 and modifications to library to support absolute paths in configuration file (latest tor will not start if there are relative paths in configuration files).

### CODE REVIEW

**Comment by jehy** [comment]
Cool! I will edit readme a little and merge this pull request today or tomorrow.

**Comment by Mechtecs** [comment]
@jehy Are you sure about that :P 
Would be nice if you could merge it :)

**Comment by jehy** [comment]
Yup, sorry. Was busy in node.js development :)
I will merge it soon (1-5 days).

**Comment by jehy** [comment]
Merged together with binary update to tor 0.3.1.9

**Comment by Mechtecs** [comment]
Thanks :)

**Comment by Perflyst** [comment]
I added the newest .aar but the symbol cannot resolved.
What should I do?
[Screenshot of the error](https://i.imgur.com/ZLwD1JF.png)

**Pull request merged**
